### ISSUE TITLE
BUG: error on <> (script) clickTrigger, after actual Click

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#105]
the script behaves correctly, it prints what it must print into the console, but after the execution ends, it shows:

745.cba41a8a.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'substring')
    at a._setDataBindingValue (745.cba41a8a.js:1:191523)
    at a.setDataBinding (CheckBoxWidget.vue:185:1)
    at a.replaceDataBinding (TemplateMixin.vue?d28e:240:1)
    at a.renderScriptDataBinding (690.0d447b5d.js:1:55225)
    at 690.0d447b5d.js:1:54845

Am I doing something wrong ?

Complete script code, bellow:

function refreshProdCategPage() {
    let ids = data.pages.prod_categories.pages[data.pages.prod_categories.cpage];
    data.instant.prod_categories = [];
    for (let iid of ids) {
        const id = iid.id;
        data.instant.prod_categories.push({
            img: data.categories[id].img,
            label: data.categories[id].label
        });
    }
}

console.log("Evrika1");
data.pages.prod_categories.cpage++;
console.log("Evrika2");
refreshProdCategPage();
console.log("Evrika3");
console.log(data.instant.prod_categories);

**Comment by Equilibrier** [comment]
I'm not sure what happened, but I recreated the screen, the script and the links and now it works without that error.
Will close the ticket now. Anyways, I will share the prototype with you, just because I have the qux -> screen -> getWidget issue, and I need it to work so that I can hide components, like you were documenting it in the help-page (scripting).

**Comment by Equilibrier** [comment]
The bug did not reproduce itself again, after recreating the components and links.
