### ISSUE TITLE
Use with vue.js

### ISSUE THREAD

**Issue by guilherme-funchal** [KlausSchaefers/quant-ux#23]
Hello, My name is Guilherme, Im Braziliam developer and Im trying to use Quant-Ux with Vue.js.

When Im try to convert the test project to Vue Js qith "quant-ux" command, I get the error bellow :

Quant-UX: Start generating code! V 2.0.1
Quant-UX: Load config <.quant-ux.json>
{}
Quant-UX: Generate <Vue (Deprecated)> for prototype
Not supported type : vue (deprecated)
/usr/local/lib/node_modules/quant-ux-cli/lib/cli.js:22
var files = generator.run(app, conf);
^

TypeError: Cannot read property 'run' of undefined
at generate (/usr/local/lib/node_modules/quant-ux-cli/lib/cli.js:22:25)
at Request._callback (/usr/local/lib/node_modules/quant-ux-cli/lib/cli.js:82:9)
at Request.self.callback (/usr/local/lib/node_modules/quant-ux-cli/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request. (/usr/local/lib/node_modules/quant-ux-cli/node_modules/request/request.js:1154:10)
at Request.emit (events.js:198:13)
at IncomingMessage. (/usr/local/lib/node_modules/quant-ux-cli/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)

**Comment by KlausSchaefers** [comment]
Hi,

the code generation is currently broken :) The best way to get your App into production is using the low code approach:

https://github.com/KlausSchaefers/vue-low-code

This will create all the code on the fly, but will still allow painless design changes. You can also read more about my reasoning here:

https://uxdesign.cc/figma-low-code-a-new-way-to-tackle-design-hand-offs-a72cb109a455

The low code tech works with Figma and Quant-UX, but with quant-ux the web service calls etc still work.

Code generation will come back, but this will still take some time. Sorry for the trouble!

**Comment by guilherme-funchal** [comment]
Thanks

I dont understand how I can start a new project in vue.js and connect with quant-ux. Do you have some howto ?
