### ISSUE TITLE
"Uncaught (in promise) Error: fillString() > Not all parameters replaced!"

### ISSUE THREAD

**Issue by rozek** [KlausSchaefers/quant-ux#280]
I'm desperately trying to submit some JSON data (bound to a variable) to a Web Service, but I always get the error

Uncaught (in promise) Error: fillString() > Not all parameters replaced! ...
at async o.buildData (RestEngine.js:65:13)
at async RestEngine.js:263:17

and my data got heavily blown up - as if the "RestEngine" would interpret my data (what it shouldn't).

How can I solve this problem?

**Comment by rozek** [comment]
well, I solved it by "escaping" any "${" in my data - which is ugly, but feasible.

**Comment by KlausSchaefers** [comment]
Ok, that is a interesting edge case. The templating mechanism of the rest engine seems to have a bug in here.

**Comment by rozek** [comment]
yeah, the classical "escaping" problem...

**Comment by KlausSchaefers** [comment]
Hi, I think I fixed the issue. Could you test again?

**Comment by rozek** [comment]
sorry for the late response, but I had to meet a submission deadline for another project first...

I'm running Quant-UX in a local Docker container. Is there a new Docker file somewhere?
