### ISSUE TITLE
Simulator shows blank screen plus QR code

### ISSUE THREAD

**Issue by rozek** [KlausSchaefers/quant-ux#282]
Ok, so I played around a bit, added most of the "Wireframe" widgets to a single screen and then tried to "Simulate"...but the simulator just displayed a blank screen together with a QR code - accompanied by the following error messages in the browser console:

RenderMixin.vue:90 TypeError: Cannot read properties of undefined (reading 'forEach')
    at a.wireContainer (RenderMixin.vue:447:1)
    at a.createWidget (RenderMixin.vue:432:1)
    at a.createScreen (RenderMixin.vue:215:1)
    at a.renderScreen (RenderMixin.vue:67:1)
    at a.render (RenderMixin.vue:34:1)
    at a.startSimilator (Simulator.vue:477:1)
renderScreen @ RenderMixin.vue:90
render @ RenderMixin.vue:34
startSimilator @ Simulator.vue:477
await in startSimilator (async)
setModel @ Simulator.vue:383
(anonymous) @ _Dialogs.vue:1039
setTimeout (async)
_showMobileTest @ _Dialogs.vue:1037
startSimilator @ _Dialogs.vue:888
(anonymous) @ lang.js:13
RenderMixin.vue:91 Simualtor.render() > Cannot read properties of undefined (reading 'forEach')
renderScreen @ RenderMixin.vue:91
render @ RenderMixin.vue:34
startSimilator @ Simulator.vue:477
await in startSimilator (async)
setModel @ Simulator.vue:383
(anonymous) @ _Dialogs.vue:1039
setTimeout (async)
_showMobileTest @ _Dialogs.vue:1037
startSimilator @ _Dialogs.vue:888
(anonymous) @ lang.js:13
RenderMixin.vue:92 TypeError: Cannot read properties of undefined (reading 'forEach')
    at a.wireContainer (RenderMixin.vue:447:1)
    at a.createWidget (RenderMixin.vue:432:1)
    at a.createScreen (RenderMixin.vue:215:1)
    at a.renderScreen (RenderMixin.vue:67:1)
    at a.render (RenderMixin.vue:34:1)
    at a.startSimilator (Simulator.vue:477:1)
renderScreen @ RenderMixin.vue:92
render @ RenderMixin.vue:34
startSimilator @ Simulator.vue:477
await in startSimilator (async)
setModel @ Simulator.vue:383
(anonymous) @ _Dialogs.vue:1039
setTimeout (async)
_showMobileTest @ _Dialogs.vue:1037
startSimilator @ _Dialogs.vue:888
(anonymous) @ lang.js:13
Logger.js:43 Error TypeError: Cannot read properties of undefined (reading 'forEach')
    at a.wireContainer (RenderMixin.vue:447:1)
    at a.createWidget (RenderMixin.vue:432:1)
    at a.createScreen (RenderMixin.vue:215:1)
    at a.renderScreen (RenderMixin.vue:67:1)
    at a.render (RenderMixin.vue:34:1)
    at a.startSimilator (Simulator.vue:477:1)

**Comment by rozek** [comment]
Oh, I _may_ have found the underlying cause for the blank simulator screen: as one of my last widgets I added a "Screen Segment" without specifying a screen segment - and the simulator does not seem to like that...

**Comment by KlausSchaefers** [comment]
Thanks for finding that bug. I will fix it later this week

Andreas Rozek ***@***.***> schrieb am Sa., 23. März 2024,
17:10:
