### ISSUE TITLE
more errors in the browser console

### ISSUE THREAD

**Issue by rozek** [KlausSchaefers/quant-ux#283]
92MouseMixin.vue:72 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at a.initMouseEvent (MouseMixin.vue:72:1)
    at a.onMouseMove (MouseMixin.vue:46:1)
    at HTMLDivElement.<anonymous> (lang.js:13:53)

(The "92" indicates the number of times the error occured)

Unfortunately, I cannot tell you _when_ the error occurred, just that it is there (together with a stack trace)

**Comment by KlausSchaefers** [comment]
Can you add ***@***.*** as a team member? I will have a
look.

Andreas Rozek ***@***.***> schrieb am Sa., 23. März 2024,
17:06:

**Comment by rozek** [comment]
sorry for the late response, but I had to meet a submission deadline for another project first...

I'm running Quant-UX in a local docker container...
